=== adoptium/aqa-tests/TestConfig/playlist.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="test" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:all>
              <xs:element name="featureIds" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="featureId" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="testCaseName"/>
              <xs:element name="variations" minOccurs="0" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="variation" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="command"/>
              <xs:element type="xs:string" name="prologueTag" minOccurs="0"/>
              <xs:element type="xs:string" name="successCriteria" minOccurs="0"/>
              <xs:element type="xs:string" name="platforms" minOccurs="0"/>
              <xs:element type="xs:string" name="platformRequirements" minOccurs="0"/>
              <xs:element type="xs:string" name="id" minOccurs="0"/>
              <xs:element type="xs:string" name="dependencies" minOccurs="0"/>
              <xs:element type="xs:string" name="subsets" minOccurs="0"/>
              <xs:element name="tags" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="tag" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="subsets" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="subset" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== adoptium/aqa-tests/OpenJDK_Playlist/disabledplaylist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TestConfig/playlist.xsd">
	<test>
		<testCaseName>OpenJDK_stackWalker</testCaseName>
		<command>$(JAVA_COMMAND) $(CMPRSSPTRS) -Xmx512m -jar $(Q)$(JTREG_DIR)$(D)lib$(D)jtreg.jar$(Q) \
	-agentvm -a -ea -esa -v:fail,error,time -retain:fail,error -ignore:quiet -timeoutFactor:4 -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	$(Q)$(JTREG_TEST_DIR)$(D)java$(D)lang$(D)StackWalker$(Q); \
	$(TEST_STATUS)</command>
		<subsets>
			<subset>SE90</subset>
		</subsets>
		<tags>
			<tag>openjdk</tag>
		</tags>
	</test>
	<test>
		<testCaseName>jdk_awt</testCaseName>
		<command>export DISPLAY=:1; $(JAVA_COMMAND) -Xmx512m -jar $(Q)$(JTREG_DIR)$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS)  -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	$(Q)$(JTREG_TEST_DIR):jdk_awt$(Q); \
	$(TEST_STATUS)</command>
		<subsets>
			<subset>SE80</subset>
		</subsets>
		<tags>
			<tag>extended</tag>
		</tags>
	</test>
	<test>
		<testCaseName>jdk_sound</testCaseName>
		<command>$(JAVA_COMMAND) -Xmx512m -jar $(Q)$(JTREG_DIR)$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS)  -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	$(Q)$(JTREG_TEST_DIR):jdk_sound$(Q); \
	$(TEST_STATUS)</command>
		<subsets>
			<subset>SE80</subset>
		</subsets>
		<tags>
			<tag>extended</tag>
		</tags>
	</test>
	<test>
		<testCaseName>jdk_swing</testCaseName>
		<command>export DISPLAY=:1; $(JAVA_COMMAND) -Xmx512m -jar $(Q)$(JTREG_DIR)$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS)  -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	$(Q)$(JTREG_TEST_DIR):jdk_swing$(Q); \
	$(TEST_STATUS)</command>
		<subsets>
			<subset>SE80</subset>
		</subsets>
		<tags>
			<tag>extended</tag>
		</tags>
	</test>
</playlist>

=== adoptium/aqa-tests/example/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TestConfig/playlist.xsd">
	<test>
		<testCaseName>SanityTestExample</testCaseName>
		<variations>
			<variation>-Xint</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)example.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames exampleTest \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux,arch.x86,bits.64</platformRequirements>
		<tags>
			<tag>sanity</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
		<test>
		<testCaseName>ExtendedTestExample</testCaseName>
		<variations>
			<variation>-Xint</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(TEST_RESROOT)$(D)example.jar$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames exampleTest \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux,arch.x86,bits.64</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
</playlist>

=== adoptium/aqa-tests/systemtest/exclude_playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TestConfig/playlist.xsd">
	<test>
		<testCaseName>HCRLateAttachWorkload</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>export JAVA_HOME=$(JDK_HOME)$(D)  && \
	perl $(TEST_RESROOT)$(D)stf$(D)stf.core$(D)scripts$(D)stf.pl  \
	-test-root=$(Q)$(TEST_RESROOT)$(D)stf;$(TEST_RESROOT)$(D)openjdk-systemtest$(Q) \
	-systemtest-prereqs=$(Q)$(TEST_RESROOT)$(D)systemtest_prereqs$(Q)  \
	-results-root=$(REPORTDIR)  \
	-test=HCRLateAttachWorkload; \
	$(TEST_STATUS)</command>	
		<tags>
			<tag>system</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
</playlist>

=== adoptium/aqa-tests/thirdparty_containers/scala/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../TestConfig/playlist.xsd">
	<test>
		<testCaseName>scala_test</testCaseName>
		<command>docker run -it --rm -v $(JDK_HOME):/java  adoptopenjdk-scala-test:latest "jvm pos neg"</command>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
		<tags>
			<tag>external</tag>
		</tags>
	</test>
</playlist>
